const colors = {
  light: {
    text: "#1A0533",
    tint: "#6D28D9",
    background: "#F5F3FF",
    foreground: "#1A0533",
    card: "#FFFFFF",
    cardForeground: "#1A0533",
    primary: "#6D28D9",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#4C1D95",
    muted: "#EDE9FE",
    mutedForeground: "#7C6FA0",
    accent: "#0EA5E9",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDD6FE",
    input: "#EDE9FE",
    success: "#22C55E",
    warning: "#F59E0B",
    gradientStart: "#6D28D9",
    gradientEnd: "#4C1D95",
    gradientAccent: "#0EA5E9",
  },

  dark: {
    text: "#EEEEFF",
    tint: "#A78BFA",
    background: "#0B0B14",
    foreground: "#EEEEFF",
    card: "#13131F",
    cardForeground: "#EEEEFF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A2E",
    secondaryForeground: "#C4B5FD",
    muted: "#1A1A2E",
    mutedForeground: "#6B6B8A",
    accent: "#0EA5E9",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E30",
    input: "#1A1A2E",
    success: "#22C55E",
    warning: "#F59E0B",
    gradientStart: "#4C1D95",
    gradientEnd: "#1E1B4B",
    gradientAccent: "#0369A1",
  },

  radius: 14,
};

export default colors;
