kind = "mobile"
previewPath = "/"
title = "HTML Creator"
version = "1.0.0"
id = "artifacts/mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 18115

[services.development]
run = "pnpm --filter @workspace/mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mobile", "run", "serve" ]

[services.env]
PORT = "18115"
BASE_PATH = "/"

[[services]]
name = "api"
paths = [ "/api" ]
localPort = 3000

[services.development]
run = "PORT=3000 pnpm --filter @workspace/api-server run dev"

[services.env]
PORT = "3000"
